FactoryBot.define do
  factory :page do
    association :project
    sequence(:name) { |n| "Page #{n}" }
    path            { "/path-#{SecureRandom.hex(4)}" }
    enabled         { true }
    position        { 0 }
    hide_selectors  { [] }
    mask_selectors  { [] }
    # slug is auto-generated by before_validation callback from name

    trait :disabled do
      enabled { false }
    end

    trait :with_actions do
      actions do
        [
          { "action" => "wait", "value" => "1000" },
          { "action" => "scroll", "value" => "down" }
        ]
      end
    end
  end
end
