# These are supported funding model platforms

github: [brainz-lab]
# patreon: brainzlab
# open_collective: brainzlab
# ko_fi: brainzlab
# tidelift: rubygems/brainzlab
custom: ['https://brainzlab.ai/sponsor']
